In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv("Breast_Cancer.csv")

: 

In [3]:
data.head()

Age   Race Marital Status T Stage  N Stage 6th Stage  \
0   68  White        Married       T1      N1       IIA   
1   50  White        Married       T2      N2      IIIA   
2   58  White       Divorced       T3      N3      IIIC   
3   58  White        Married       T1      N1       IIA   
4   47  White        Married       T2      N1       IIB   

               differentiate Grade   A Stage  Tumor Size Estrogen Status  \
0      Poorly differentiated     3  Regional           4        Positive   
1  Moderately differentiated     2  Regional          35        Positive   
2  Moderately differentiated     2  Regional          63        Positive   
3      Poorly differentiated     3  Regional          18        Positive   
4      Poorly differentiated     3  Regional          41        Positive   

  Progesterone Status  Regional Node Examined  Reginol Node Positive  \
0            Positive                      24                      1   
1            Positive                      14                      5   
2            Positive                      14                      7   
3            Positive                       2                      1   
4            Positive                       3                      1   

   Survival Months Status  
0               60  Alive  
1               62  Alive  
2               75  Alive  
3               84  Alive  
4               50  Alive

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4024 entries, 0 to 4023
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Age                     4024 non-null   int64 
 1   Race                    4024 non-null   object
 2   Marital Status          4024 non-null   object
 3   T Stage                 4024 non-null   object
 4   N Stage                 4024 non-null   object
 5   6th Stage               4024 non-null   object
 6   differentiate           4024 non-null   object
 7   Grade                   4024 non-null   object
 8   A Stage                 4024 non-null   object
 9   Tumor Size              4024 non-null   int64 
 10  Estrogen Status         4024 non-null   object
 11  Progesterone Status     4024 non-null   object
 12  Regional Node Examined  4024 non-null   int64 
 13  Reginol Node Positive   4024 non-null   int64 
 14  Survival Months         4024 non-null   int64 
 15  Stat

In [5]:
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
4019    False
4020    False
4021    False
4022    False
4023    False
Length: 4024, dtype: bool

In [6]:
data.isna().sum()

Age                       0
Race                      0
Marital Status            0
T Stage                   0
N Stage                   0
6th Stage                 0
differentiate             0
Grade                     0
A Stage                   0
Tumor Size                0
Estrogen Status           0
Progesterone Status       0
Regional Node Examined    0
Reginol Node Positive     0
Survival Months           0
Status                    0
dtype: int64

In [7]:
data.drop_duplicates(inplace=True)

In [8]:
data.columns

Index(['Age', 'Race', 'Marital Status', 'T Stage ', 'N Stage', '6th Stage',
       'differentiate', 'Grade', 'A Stage', 'Tumor Size', 'Estrogen Status',
       'Progesterone Status', 'Regional Node Examined',
       'Reginol Node Positive', 'Survival Months', 'Status'],
      dtype='object')

In [9]:
data.shape

(4023, 16)

In [10]:
data.Status.unique()

array(['Alive', 'Dead'], dtype=object)

In [11]:
status_mapping = {
    'Alive': 1,
    'Dead': 0,
}

# Apply the mapping to the 'Status' column
data['Status'] = data['Status'].map(status_mapping)

In [12]:
data["Status"].unique()

array([1, 0], dtype=int64)

In [13]:
data['Survival Months'].unique()

array([ 60,  62,  75,  84,  50,  89,  54,  14,  70,  92,  64,  56,  38,
        49, 105, 107,  77,  81,  78, 102,  98,  82,  86,  52,  90,  31,
        37, 103,  42,  61,  63,  39,  59,  71,  74,  73,  91, 106,  80,
        44,  85,  79, 104,  12,  95,  55, 101,  65,  72,  57,  87,  40,
        25,   8,  53,  58,  24,  66,  69,  93,  94, 100,  96,  41,  67,
        51,  13,  11,  47,  23,  45,  68,  76,  15,  16,  99,   7,  48,
        88,  34,  97,  83,  17,   3,  22,  30,   6,  32,   9,   5,  10,
        19,  18,  35,  27,  36,   4,  29,  33,  26,  20,  28,  43,   1,
        46,  21,   2], dtype=int64)

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4023 entries, 0 to 4023
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Age                     4023 non-null   int64 
 1   Race                    4023 non-null   object
 2   Marital Status          4023 non-null   object
 3   T Stage                 4023 non-null   object
 4   N Stage                 4023 non-null   object
 5   6th Stage               4023 non-null   object
 6   differentiate           4023 non-null   object
 7   Grade                   4023 non-null   object
 8   A Stage                 4023 non-null   object
 9   Tumor Size              4023 non-null   int64 
 10  Estrogen Status         4023 non-null   object
 11  Progesterone Status     4023 non-null   object
 12  Regional Node Examined  4023 non-null   int64 
 13  Reginol Node Positive   4023 non-null   int64 
 14  Survival Months         4023 non-null   int64 
 15  Status   

In [15]:
data.Race.unique()

array(['White', 'Black', 'Other'], dtype=object)

In [16]:
race_mapping = {
    'White': 0,
    'Black': 1,
    'Other': 2
}

# Apply the mapping to the 'Status' column
data['Race'] = data['Race'].map(race_mapping)

In [17]:
data.Race.unique()

array([0, 1, 2], dtype=int64)

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4023 entries, 0 to 4023
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Age                     4023 non-null   int64 
 1   Race                    4023 non-null   int64 
 2   Marital Status          4023 non-null   object
 3   T Stage                 4023 non-null   object
 4   N Stage                 4023 non-null   object
 5   6th Stage               4023 non-null   object
 6   differentiate           4023 non-null   object
 7   Grade                   4023 non-null   object
 8   A Stage                 4023 non-null   object
 9   Tumor Size              4023 non-null   int64 
 10  Estrogen Status         4023 non-null   object
 11  Progesterone Status     4023 non-null   object
 12  Regional Node Examined  4023 non-null   int64 
 13  Reginol Node Positive   4023 non-null   int64 
 14  Survival Months         4023 non-null   int64 
 15  Status   

In [19]:
data['Marital Status'].unique()

array(['Married', 'Divorced', 'Single ', 'Widowed', 'Separated'],
      dtype=object)

In [20]:
from sklearn.preprocessing import LabelEncoder

In [21]:
LE = LabelEncoder()

In [22]:
data['Marital Status'] = LE.fit_transform(data['Marital Status'])

In [23]:
data['Marital Status'].unique()

array([1, 0, 3, 4, 2])

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4023 entries, 0 to 4023
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Age                     4023 non-null   int64 
 1   Race                    4023 non-null   int64 
 2   Marital Status          4023 non-null   int32 
 3   T Stage                 4023 non-null   object
 4   N Stage                 4023 non-null   object
 5   6th Stage               4023 non-null   object
 6   differentiate           4023 non-null   object
 7   Grade                   4023 non-null   object
 8   A Stage                 4023 non-null   object
 9   Tumor Size              4023 non-null   int64 
 10  Estrogen Status         4023 non-null   object
 11  Progesterone Status     4023 non-null   object
 12  Regional Node Examined  4023 non-null   int64 
 13  Reginol Node Positive   4023 non-null   int64 
 14  Survival Months         4023 non-null   int64 
 15  Status   

In [25]:
data['T Stage '].unique()

array(['T1', 'T2', 'T3', 'T4'], dtype=object)

In [26]:
data['T Stage '] = LE.fit_transform(data['T Stage '])

In [27]:
data['T Stage '].unique()

array([0, 1, 2, 3])

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4023 entries, 0 to 4023
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Age                     4023 non-null   int64 
 1   Race                    4023 non-null   int64 
 2   Marital Status          4023 non-null   int32 
 3   T Stage                 4023 non-null   int32 
 4   N Stage                 4023 non-null   object
 5   6th Stage               4023 non-null   object
 6   differentiate           4023 non-null   object
 7   Grade                   4023 non-null   object
 8   A Stage                 4023 non-null   object
 9   Tumor Size              4023 non-null   int64 
 10  Estrogen Status         4023 non-null   object
 11  Progesterone Status     4023 non-null   object
 12  Regional Node Examined  4023 non-null   int64 
 13  Reginol Node Positive   4023 non-null   int64 
 14  Survival Months         4023 non-null   int64 
 15  Status   

In [29]:
data['N Stage'].unique()

array(['N1', 'N2', 'N3'], dtype=object)

In [30]:
data['N Stage'] = LE.fit_transform(data['N Stage'])

In [31]:
data['N Stage'].unique()

array([0, 1, 2])

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4023 entries, 0 to 4023
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Age                     4023 non-null   int64 
 1   Race                    4023 non-null   int64 
 2   Marital Status          4023 non-null   int32 
 3   T Stage                 4023 non-null   int32 
 4   N Stage                 4023 non-null   int32 
 5   6th Stage               4023 non-null   object
 6   differentiate           4023 non-null   object
 7   Grade                   4023 non-null   object
 8   A Stage                 4023 non-null   object
 9   Tumor Size              4023 non-null   int64 
 10  Estrogen Status         4023 non-null   object
 11  Progesterone Status     4023 non-null   object
 12  Regional Node Examined  4023 non-null   int64 
 13  Reginol Node Positive   4023 non-null   int64 
 14  Survival Months         4023 non-null   int64 
 15  Status   

In [33]:
data["6th Stage"].unique()

array(['IIA', 'IIIA', 'IIIC', 'IIB', 'IIIB'], dtype=object)

In [34]:
data['6th Stage'] = LE.fit_transform(data['6th Stage'])

In [35]:
data["6th Stage"].unique()

array([0, 2, 4, 1, 3])

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4023 entries, 0 to 4023
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Age                     4023 non-null   int64 
 1   Race                    4023 non-null   int64 
 2   Marital Status          4023 non-null   int32 
 3   T Stage                 4023 non-null   int32 
 4   N Stage                 4023 non-null   int32 
 5   6th Stage               4023 non-null   int32 
 6   differentiate           4023 non-null   object
 7   Grade                   4023 non-null   object
 8   A Stage                 4023 non-null   object
 9   Tumor Size              4023 non-null   int64 
 10  Estrogen Status         4023 non-null   object
 11  Progesterone Status     4023 non-null   object
 12  Regional Node Examined  4023 non-null   int64 
 13  Reginol Node Positive   4023 non-null   int64 
 14  Survival Months         4023 non-null   int64 
 15  Status   

In [37]:
data.differentiate.unique()

array(['Poorly differentiated', 'Moderately differentiated',
       'Well differentiated', 'Undifferentiated'], dtype=object)

In [38]:
data['differentiate'] = LE.fit_transform(data['differentiate'])

In [39]:
data.differentiate.unique()

array([1, 0, 3, 2])

In [40]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4023 entries, 0 to 4023
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Age                     4023 non-null   int64 
 1   Race                    4023 non-null   int64 
 2   Marital Status          4023 non-null   int32 
 3   T Stage                 4023 non-null   int32 
 4   N Stage                 4023 non-null   int32 
 5   6th Stage               4023 non-null   int32 
 6   differentiate           4023 non-null   int32 
 7   Grade                   4023 non-null   object
 8   A Stage                 4023 non-null   object
 9   Tumor Size              4023 non-null   int64 
 10  Estrogen Status         4023 non-null   object
 11  Progesterone Status     4023 non-null   object
 12  Regional Node Examined  4023 non-null   int64 
 13  Reginol Node Positive   4023 non-null   int64 
 14  Survival Months         4023 non-null   int64 
 15  Status   

In [41]:
data.Grade.unique()

array(['3', '2', '1', ' anaplastic; Grade IV'], dtype=object)

In [42]:
data[data["Grade"]==' anaplastic; Grade IV']

Age  Race  Marital Status  T Stage   N Stage  6th Stage  differentiate  \
277    52     1               3         2        2          4              2   
616    38     0               1         2        0          2              2   
618    37     1               1         2        0          2              2   
767    69     0               1         0        0          0              2   
1013   59     0               3         1        1          2              2   
1061   67     0               1         1        2          4              2   
1458   39     0               3         2        1          2              2   
1541   69     0               4         1        2          4              2   
1560   58     0               3         0        1          2              2   
1716   43     0               1         2        1          2              2   
2172   62     1               2         3        2          4              2   
2177   63     0               1         1        0          1              2   
2246   50     0               1         2        0          2              2   
2411   57     0               1         0        0          0              2   
2717   40     0               3         2        0          2              2   
3073   43     0               1         3        2          4              2   
3212   54     0               0         0        0          0              2   
3248   45     0               1         0        0          0              2   
3526   49     0               1         1        0          1              2   

                      Grade   A Stage  Tumor Size Estrogen Status  \
277    anaplastic; Grade IV  Regional         100        Positive   
616    anaplastic; Grade IV  Regional          70        Positive   
618    anaplastic; Grade IV  Regional          60        Positive   
767    anaplastic; Grade IV  Regional          20        Positive   
1013   anaplastic; Grade IV  Regional          40        Negative   
1061   anaplastic; Grade IV  Regional          21        Positive   
1458   anaplastic; Grade IV  Regional          70        Positive   
1541   anaplastic; Grade IV  Regional          28        Positive   
1560   anaplastic; Grade IV  Regional          19        Negative   
1716   anaplastic; Grade IV  Regional          75        Negative   
2172   anaplastic; Grade IV  Regional          70        Positive   
2177   anaplastic; Grade IV  Regional          25        Negative   
2246   anaplastic; Grade IV  Regional          55        Positive   
2411   anaplastic; Grade IV  Regional          18        Positive   
2717   anaplastic; Grade IV  Regional          52        Positive   
3073   anaplastic; Grade IV  Regional          59        Negative   
3212   anaplastic; Grade IV  Regional          16        Positive   
3248   anaplastic; Grade IV  Regional          13        Positive   
3526   anaplastic; Grade IV  Regional          28        Positive   

     Progesterone Status  Regional Node Examined  Reginol Node Positive  \
277             Positive                      23                     17   
616             Positive                      10                      1   
618             Positive                       5                      2   
767             Positive                      17                      3   
1013            Negative                      10                      9   
1061            Positive                      25                     17   
1458            Positive                      14                      4   
1541            Positive                      14                     13   
1560            Negative                      47                      7   
1716            Negative                      10                      5   
2172            Positive                      10                     10   
2177            Positive                      10                      2   
2246            Positive                      12 

In [43]:
data['Grade'] = LE.fit_transform(data['Grade'])

In [44]:
data.Grade.unique()

array([3, 2, 1, 0])

In [45]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4023 entries, 0 to 4023
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Age                     4023 non-null   int64 
 1   Race                    4023 non-null   int64 
 2   Marital Status          4023 non-null   int32 
 3   T Stage                 4023 non-null   int32 
 4   N Stage                 4023 non-null   int32 
 5   6th Stage               4023 non-null   int32 
 6   differentiate           4023 non-null   int32 
 7   Grade                   4023 non-null   int32 
 8   A Stage                 4023 non-null   object
 9   Tumor Size              4023 non-null   int64 
 10  Estrogen Status         4023 non-null   object
 11  Progesterone Status     4023 non-null   object
 12  Regional Node Examined  4023 non-null   int64 
 13  Reginol Node Positive   4023 non-null   int64 
 14  Survival Months         4023 non-null   int64 
 15  Status   

In [46]:
data['A Stage'].unique()

array(['Regional', 'Distant'], dtype=object)

In [47]:
data['A Stage'] = LE.fit_transform(data['A Stage'])

In [48]:
data['A Stage'].unique()

array([1, 0])

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4023 entries, 0 to 4023
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Age                     4023 non-null   int64 
 1   Race                    4023 non-null   int64 
 2   Marital Status          4023 non-null   int32 
 3   T Stage                 4023 non-null   int32 
 4   N Stage                 4023 non-null   int32 
 5   6th Stage               4023 non-null   int32 
 6   differentiate           4023 non-null   int32 
 7   Grade                   4023 non-null   int32 
 8   A Stage                 4023 non-null   int32 
 9   Tumor Size              4023 non-null   int64 
 10  Estrogen Status         4023 non-null   object
 11  Progesterone Status     4023 non-null   object
 12  Regional Node Examined  4023 non-null   int64 
 13  Reginol Node Positive   4023 non-null   int64 
 14  Survival Months         4023 non-null   int64 
 15  Status   

In [50]:
data['Estrogen Status'].unique()

array(['Positive', 'Negative'], dtype=object)

In [51]:
data['Estrogen Status'] = LE.fit_transform(data['Estrogen Status'])

In [52]:
data['Progesterone Status'].unique()

array(['Positive', 'Negative'], dtype=object)

In [53]:
data['Progesterone Status'] = LE.fit_transform(data['Progesterone Status'])

In [54]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4023 entries, 0 to 4023
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     4023 non-null   int64
 1   Race                    4023 non-null   int64
 2   Marital Status          4023 non-null   int32
 3   T Stage                 4023 non-null   int32
 4   N Stage                 4023 non-null   int32
 5   6th Stage               4023 non-null   int32
 6   differentiate           4023 non-null   int32
 7   Grade                   4023 non-null   int32
 8   A Stage                 4023 non-null   int32
 9   Tumor Size              4023 non-null   int64
 10  Estrogen Status         4023 non-null   int32
 11  Progesterone Status     4023 non-null   int32
 12  Regional Node Examined  4023 non-null   int64
 13  Reginol Node Positive   4023 non-null   int64
 14  Survival Months         4023 non-null   int64
 15  Status                  40

In [55]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [56]:
X = data.drop('Status',axis=1)

In [57]:
X


Age  Race  Marital Status  T Stage   N Stage  6th Stage  differentiate  \
0      68     0               1         0        0          0              1   
1      50     0               1         1        1          2              0   
2      58     0               0         2        2          4              0   
3      58     0               1         0        0          0              1   
4      47     0               1         1        0          1              1   
...   ...   ...             ...       ...      ...        ...            ...   
4019   62     2               1         0        0          0              0   
4020   56     0               0         1        1          2              0   
4021   68     0               1         1        0          1              0   
4022   58     1               0         1        0          1              0   
4023   46     0               1         1        0          1              0   

      Grade  A Stage  Tumor Size  Estrogen Status  Progesterone Status  \
0         3        1           4                1                    1   
1         2        1          35                1                    1   
2         2        1          63                1                    1   
3         3        1          18                1                    1   
4         3        1          41                1                    1   
...     ...      ...         ...              ...                  ...   
4019      2        1           9                1                    1   
4020      2        1          46                1                    1   
4021      2        1          22                1                    0   
4022      2        1          44                1                    1   
4023      2        1          30                1                    1   

      Regional Node Examined  Reginol Node Positive  Survival Months  
0                         24                      1               60  
1                         14                      5               62  
2                         14                      7               75  
3                          2                      1               84  
4                          3                      1               50  
...                      ...                    ...              ...  
4019                       1                      1               49  
4020                      14                      8               69  
4021                      11                      3               69  
4022                      11                      1               72  
4023                       7                      2              100  

[4023 rows x 15 columns]

In [58]:
Y = data["Status"]

In [59]:
Y


0       1
1       1
2       1
3       1
4       1
       ..
4019    1
4020    1
4021    1
4022    1
4023    1
Name: Status, Length: 4023, dtype: int64

In [60]:
Y.value_counts()

Status
1    3407
0     616
Name: count, dtype: int64

In [61]:
X_train,X_test,Y_train,Y_test =train_test_split(X,Y,test_size=0.2,random_state=0)

In [62]:
LGR = LogisticRegression()

In [63]:
LGR.fit(X_train,Y_train)

C:\Users\Muhammad Ramzan LLC\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [64]:
Y_train_pred = LGR.predict(X_train)

In [65]:
pd.DataFrame({'Original_Y_test':Y_train,
               'Predicted Y_test': Y_train_pred})

Original_Y_test  Predicted Y_test
3095                0                 0
4016                1                 1
554                 1                 1
3567                1                 1
1772                1                 1
...               ...               ...
836                 1                 1
3265                1                 1
1654                1                 1
2608                1                 1
2733                1                 1

[3218 rows x 2 columns]

In [66]:
accuracy_score(Y_train,Y_train_pred)

0.896519577377253

In [67]:
confusion_matrix(Y_train,Y_train_pred)

array([[ 218,  270],
       [  63, 2667]], dtype=int64)

In [68]:
print(classification_report(Y_train,Y_train_pred))

              precision    recall  f1-score   support

           0       0.78      0.45      0.57       488
           1       0.91      0.98      0.94      2730

    accuracy                           0.90      3218
   macro avg       0.84      0.71      0.75      3218
weighted avg       0.89      0.90      0.88      3218



In [69]:
Y_test_pred = LGR.predict(X_test)

In [70]:
pd.DataFrame({'Original_Y_test':Y_test,
               'Predicted Y_test': Y_test_pred})

Original_Y_test  Predicted Y_test
1494                1                 1
2588                1                 0
892                 0                 1
1953                1                 1
87                  1                 1
...               ...               ...
3558                1                 1
159                 0                 0
3885                1                 1
3054                1                 1
3565                1                 1

[805 rows x 2 columns]

In [71]:
accuracy_score(Y_test,Y_test_pred)

0.9006211180124224

In [72]:
confusion_matrix(Y_test,Y_test_pred)

array([[ 63,  65],
       [ 15, 662]], dtype=int64)

In [73]:
print(classification_report(Y_test,Y_test_pred))

              precision    recall  f1-score   support

           0       0.81      0.49      0.61       128
           1       0.91      0.98      0.94       677

    accuracy                           0.90       805
   macro avg       0.86      0.74      0.78       805
weighted avg       0.89      0.90      0.89       805



In [75]:
data.Status.value_counts()

Status
1    3407
0     616
Name: count, dtype: int64